# Generated by Django 3.1.3 on 2020-11-24 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('', 'Select Currency'), ('BTC', 'Bitcoin'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=False)),
                ('dest_account_provider_code', models.CharField(max_length=15, null=True)),
                ('dest_account_provider_name', models.CharField(max_length=50, null=True)),
                ('dest_account_number', models.CharField(max_length=20, null=True)),
                ('dest_account_name', models.CharField(max_length=50, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('', 'Select Currency'), ('BTC', 'Bitcoin'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=False)),
                ('source_account_provider', models.CharField(max_length=50, null=True)),
                ('source_account_number', models.CharField(max_length=20, null=True)),
                ('source_account_name', models.CharField(max_length=50, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
