# Generated by Django 3.1.3 on 2020-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis'), ('BTC', 'Bitcoin')], max_length=3),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis')], max_length=3),
        ),
    ]
