# Generated by Django 3.1.3 on 2020-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20201130_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngn_to_ghs', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ghs_to_ngn', models.DecimalField(decimal_places=5, max_digits=8)),
                ('btc_to_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('btc_to_ghs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='outflow',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedis'), ('NGN', 'Nigerian Naira')], max_length=3),
        ),
    ]
