# Generated by Django 3.1.3 on 2021-02-16 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20201228_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='rates',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis')], max_length=3),
        ),
    ]
