# Generated by Django 3.1.3 on 2021-02-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20210216_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Rates'},
        ),
    ]
