# Generated by Django 3.1.3 on 2021-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20210216_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='source_account_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
