# Generated by Django 3.1.3 on 2021-02-19 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20210217_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=30, unique=True)),
                ('inflow_currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis'), ('BTC', 'Bitcoin')], max_length=3)),
                ('inflow_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('inflow_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outflow_currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis'), ('BTC', 'Bitcoin')], max_length=3)),
                ('outflow_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outflow_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outflow_amount_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revenue_in_outflow_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='inflow',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis'), ('BTC', 'Bitcoin')], max_length=3),
        ),
    ]
