# Generated by Django 3.1.3 on 2021-03-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20210219_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
