# Generated by Django 3.1.3 on 2021-03-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_auto_20210315_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionreport',
            old_name='revenue_in_outflow_currency',
            new_name='revenue',
        ),
        migrations.RemoveField(
            model_name='transactionreport',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='transactionreport',
            name='revenue_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghana Cedis'), ('BTC', 'Bitcoin')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
