# Generated by Django 3.1.3 on 2021-03-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20210315_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionReport',
            new_name='Report',
        ),
    ]
