# Generated by Django 3.1.3 on 2021-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_auto_20210315_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='fee',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='fee',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
