# Generated by Django 3.1.3 on 2021-07-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_auto_20210609_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
